[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["brain_games"]

[project]
name = "brain-games"
version = "0.1.0"
requires-python = ">=3.10"
[project.scripts]
brain-games = "brain_games.scripts.brain_games:main"
